name: Build reusable action

description: Reusable action to run tests and sonar analysis

inputs:
  sonar_token:
    description: "Sonarcloud token"
    required: true
  build_artifact:
    description: boolean flag to determine whether artifact should be built
    required: false
    default: "false"
  run_id:
    description: job run id
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run unit tests
      run: mvn spotless:check test
      shell: bash
    - name: Checkstyle analysis
      run: mvn checkstyle:checkstyle
      shell: bash
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{inputs.sonar_token}}
      with:
        args: >
          -Dsonar.organization=lloydamt
          -Dsonar.projectKey=lloydamt_suggestions-api
          -Dsonar.sources=src/main
          -Dsonar.tests=src/test
          -Dsonar.java.binaries=target/classes
          -Dsonar.java.test.binaries=target/test-classes
          -Dsonar.junit.reportPaths=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
    - name: build artifact
      run: mvn install -DskipTests
      shell: bash
      if: ${{inputs.build_artifact}} == "true"
    - name: rename artifact
      run: |
        cd target
        mv *.jar ${{inputs.run_id}}.jar
      shell: bash
      if: ${{inputs.build_artifact}} == "true"
    - uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: target/*.jar
      if: ${{inputs.build_artifact}} == "true"
