name: Run Docker build and push

description: Reusable action to build docker image

inputs:
  push:
    description: flag to enable push to registry
    required: false
    default: "false"
  username:
    description: registry username
    required: true
  password:
    description: registry password
    required: true
  version:
    description: docker image version
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push }}
        tags: ${{ inputs.username }}/suggestions-api:v${{inputs.version}}
