name: Suggestions api build job

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests and build artifact
        uses: ./.github/actions/build-action
