name: Suggestions api build job

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tests and build artifact
        uses: ./.github/actions/build-action
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/docker-build
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
