name: Publish artifact to dockerhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ELASTIC_BEANSTALK_NAME: suggestions-app-env
  ELASTIC_BEANSTALK_ENV_NAME: suggestions-app-env-env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tests and build artifact
        uses: ./.github/actions/build-action
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          run_id: ${{ github.run_id }}
          build_artifact: true
      - name: Build docker image and push to dockerhub
        uses: ./.github/actions/docker-build
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true
          version: ${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-files
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: suggestions-app
          environment_name: suggestions-app-env
          version_label: ${{ github.run_number }}
          region: us-east-1
          deployment_package: ${{ github.run_id }}.jar
