name: Publish and deploy artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  ELASTIC_BEANSTALK_NAME: suggestions-app
  ELASTIC_BEANSTALK_ENV_NAME: suggestions-app-env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tests and build artifact
        uses: ./.github/actions/build-action
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          run_id: ${{ github.run_id }}
          build_artifact: true
      - name: Build docker image and push to dockerhub
        uses: ./.github/actions/docker-build
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: build-files
  #     - name: Deploy to EB
  #       uses: einaregilsson/beanstalk-deploy@v22
  #       with:
  #         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         application_name: $ELASTIC_BEANSTALK_NAME
  #         environment_name: $ELASTIC_BEANSTALK_ENV_NAME
  #         version_label: ${{ github.run_number }}
  #         region: us-east-1
  #         deployment_package: ${{ github.run_id }}.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate deployment package
        run: zip -r deploy.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: suggestions-api
          environment_name: suggestions-api-container
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
